project_name: cnfrp

builds:
  - skip: true

checksum:
  name_template: 'cnfrp_sha256_checksums.txt'
  algorithm: sha256
  extra_files:
    - glob: ./release/packages/*

release:
  github:
    owner: wuse999
    name: cnfrp

  name_template: '{{ .ProjectName }} {{ .Tag }}'
  draft: false
  prerelease: auto

  extra_files:
    - glob: ./release/packages/*
